version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - aws s3 cp s3://megashopper-resourses/application-deploy.yml ./src/main/java/resources/application-deploy.yml
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - mv target/*.jar ./megashopper.jar

artifacts:
  files:
    - megashopper.ja