spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://megashopper.crt4qa9vzj3y.us-east-2.rds.amazonaws.com
    username: postgres
    password: TeamCFTW1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: local-revature